services:
  - docker
language: ruby
rvm:
  - 2.0
cache:
  - bundler
install:
  - travis_wait 30 bundle install --jobs=3 --retry=3 --deployment
script:
  - docker exec thor docker:build
  - bundle exec thor docker:spec
